### PR TITLE
Update bind_tweets.R

### PR DESCRIPTION
**Pull request by TimBMK**
An updated version of the bind_tweets function. The new version features the "tidy_2" format, which outputs additional variables given by the Twitter API in a tidy format. Variables can be chosen via the vars parameter and include hashtags, external URLs, mentions, annotations and context annotations. tidy_2 differs in some aspects from the tidy format's behaviour, hence the option to choose. tidy_2 explicitly removes duplicates in the data by tweet_id and adds TRUE/FALSE indicators for retweets, quotes and replies. Furthermore, it allows to specify how variables should be handled for quoted tweets, allowing users to choose between data from the quoted or quoting tweet. Finally, the entities of retweets are always taken from the original tweet, rather than the truncated retweet, and mentions returned have the original author removed in retweets and quotes. I found all of these variables and behaviours very useful when analyzing tweet data, so I decided to share this functionality with all academictwitteR users.

I've tried to account for all possible data structures, missing variables in the Twitter payload, etc., but I'd be greatful for more testing with more and different data. The function runs reasonably fast for small-ish datasets, but tidy_2 does take more computing time than the native tidy format. For very large datasets, this may become an issue, so I'd be grateful if you could point me to any performance issues and improvements.

With some data, I'm getting an error related to the .gen_raw() function ("Column `id` doesn't exist.") for both the tidy_2 and original tidy format. This seems to be an issue also with the native bind_tweets function and tidy format since updating to 0.3.1, so I'm not sure what's going on there and if the error is reproducable. I also left the .gen_raw() function and tidy format untouched, so I am having a bit of a hard time understanding what's going on there. It'd be great if you could see if you encounter the same error and maybe help troubleshoot it.

### CODE REVIEW

**Comment by chainsawriot** [comment]
@TimBMK Thanks for this. There are several initial queries

1. Would it be better to just use `tidy2` rather than `tidy_2`?
2. Using tidyverse functions in R package is quite tricky compared to in an analytic scenario. Specifically, one needs to use `rlang::.data` ([ref](https://rlang.r-lib.org/reference/dot-data.html)) for the column names, e.g. 

https://github.com/cjbarrie/academictwitteR/blob/2809432aaea388e7bb016a1f15f24787e8d05586/R/bind_tweets.R#L110

Therefore, these naked column names would generate problems in R CMD CHECK

https://github.com/TimBMK/academictwitteR/blob/abfec0d88c1958d80dacc6ecc1288a785365134e/R/bind_tweets.R#L132

My recommendation is to check regularly: `devtools::check()`.

3. Initial check suggests that your PR doesn't break old tests. But there is no test for the new functionalities. It would be nice if you can generate some test cases. But if it is not possible, could you please at least make sure the function works for the `commtwitter`, `hk1`, `hk2`, `hk3` and `reuters` in the [testdata](https://github.com/cjbarrie/academictwitteR/tree/master/tests/testdata) directory? The last one is especially important.

**Comment by chainsawriot** [comment]
the `hk2` and `hk3` don't work.

``` r
devtools::load_all("~/dev/academictwitteR")
#> ℹ Loading academictwitteR

bind_tweets("~/dev/academictwitteR/tests/testdata/hk2", output_format = "tidy")
#> # A tibble: 3,498 × 31
#>    tweet_id      user_username text  possibly_sensit… created_at conversation_id
#>    <chr>         <chr>         <chr> <lgl>            <chr>      <chr>          
#>  1 140718521713… TsuiJacky1    "@sr… FALSE            2021-06-2… 14070274279986…
#>  2 140718517281… TsuiJacky1    "@ni… FALSE            2021-06-2… 14070232122028…
#>  3 140718513379… TsuiJacky1    "@in… FALSE            2021-06-2… 14071029569656…
#>  4 140718512507… SiDana_hk     "RT … FALSE            2021-06-2… 14071851250797…
#>  5 140718511845… earthmatterg  "RT … FALSE            2021-06-2… 14071851184568…
#>  6 140718511283… Bruce13208572 "RT … FALSE            2021-06-2… 14071851128364…
#>  7 140718510125… TsuiJacky1    "@Ne… FALSE            2021-06-2… 14071085720816…
#>  8 140718507010… TsuiJacky1    "@Bl… FALSE            2021-06-2… 14070508388838…
#>  9 140718503113… TsuiJacky1    "@Yo… FALSE            2021-06-2… 14069638756150…
#> 10 140718469321… justeatingu   "RT … FALSE            2021-06-2… 14071846932130…
#> # … with 3,488 more rows, and 25 more variables: source <chr>,
#> #   in_reply_to_user_id <chr>, lang <chr>, author_id <chr>,
#> #   user_description <chr>, user_name <chr>, user_protected <lgl>,
#> #   user_profile_image_url <chr>, user_url <chr>, user_location <chr>,
#> #   user_created_at <chr>, user_verified <lgl>, user_pinned_tweet_id <chr>,
#> #   retweet_count <int>, like_count <int>, quote_count <int>,
#> #   user_tweet_count <int>, user_list_count <int>, …

bind_tweets("~/dev/academictwitteR/tests/testdata/hk2", output_format = "tidy_2")
#> Error in `h()`:
#> ! Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `... | is.na(id)`.
#> ✖ object 'id' not found

bind_tweets("~/dev/academictwitteR/tests/testdata/hk3", output_format = "tidy")
#> # A tibble: 3,499 × 31
#>    tweet_id user_username text  author_id lang  conversation_id in_reply_to_use…
#>    <chr>    <chr>         <chr> <chr>     <chr> <chr>           <chr>           
#>  1 1405857… CoolMan30000… "@Ni… 12855928… en    14057837038345… 436429668       
#>  2 1405857… Hkismyhome15  "@bu… 13358413… en    14057502201980… 20610385        
#>  3 1405857… seeseesorry   "@hk… 31710571… en    14058274242695… 914877149164789…
#>  4 1405857… PplFuture     "@hi… 12415446… en    14058141585374… 700605423       
#>  5 1405856… PplFuture     "@Se… 12415446… en    14056971777546… 529147678       
#>  6 1405855… PplFuture     "@df… 12415446… en    14057049647317… 273730280       
#>  7 1405854… PplFuture     "@na… 12415446… en    14056407796290… 16596200        
#>  8 1405854… PplFuture     "@Ba… 12415446… en    14056474718045… 250091875       
#>  9 1405853… PplFuture     "@na… 12415446… en    14057676617121… 16596200        
#> 10 1405853… PplFuture     "@bu… 12415446… en    14057502201980… 20610385        
#> # … with 3,489 more rows, and 24 more variables: possibly_sensitive <lgl>,
#> #   source <chr>, created_at <chr>, user_protected <lgl>,
#> #   user_profile_image_url <chr>, user_created_at <chr>,
#> #   user_description <chr>, user_name <chr>, user_verified <lgl>,
#> #   user_url <chr>, user_pinned_tweet_id <chr>, user_location <chr>,
#> #   retweet_count <int>, like_count <int>, quote_count <int>,
#> #   user_tweet_count <int>, user_list_count <int>, …

bind_tweets("~/dev/academictwitteR/tests/testdata/hk3", output_format = "tidy_2")
#> Error in `h()`:
#> ! Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `... | is.na(id)`.
#> ✖ object 'id' not found
```

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by chainsawriot** [comment]
The problem is with `mentions`

``` r
devtools::load_all("~/dev/academictwitteR")
#> ℹ Loading academictwitteR

bind_tweets("~/dev/academictwitteR/tests/testdata/hk3", output_format = "tidy_2", vars = c("mentions"))
#> Error in `h()`:
#> ! Problem with `filter()` input `..1`.
#> ℹ Input `..1` is `... | is.na(id)`.
#> ✖ object 'id' not found

bind_tweets("~/dev/academictwitteR/tests/testdata/hk3", output_format = "tidy_2", vars = c("hashtags", "ext_urls", "annotations", "context_annotations"))
#> # A tibble: 3,499 × 49
#>    tweet_id user_username text  author_id lang  conversation_id in_reply_to_use…
#>    <chr>    <chr>         <chr> <chr>     <chr> <chr>           <chr>           
#>  1 1405857… CoolMan30000… "@Ni… 12855928… en    14057837038345… 436429668       
#>  2 1405857… Hkismyhome15  "@bu… 13358413… en    14057502201980… 20610385        
#>  3 1405857… seeseesorry   "@hk… 31710571… en    14058274242695… 914877149164789…
#>  4 1405857… PplFuture     "@hi… 12415446… en    14058141585374… 700605423       
#>  5 1405856… PplFuture     "@Se… 12415446… en    14056971777546… 529147678       
#>  6 1405855… PplFuture     "@df… 12415446… en    14057049647317… 273730280       
#>  7 1405854… PplFuture     "@na… 12415446… en    14056407796290… 16596200        
#>  8 1405854… PplFuture     "@Ba… 12415446… en    14056474718045… 250091875       
#>  9 1405853… PplFuture     "@na… 12415446… en    14057676617121… 16596200        
#> 10 1405853… PplFuture     "@bu… 12415446… en    14057502201980… 20610385        
#> # … with 3,489 more rows, and 42 more variables: possibly_sensitive <lgl>,
#> #   source <chr>, created_at <chr>, user_protected <lgl>,
#> #   user_profile_image_url <chr>, user_created_at <chr>,
#> #   user_description <chr>, user_name <chr>, user_verified <lgl>,
#> #   user_url <chr>, user_pinned_tweet_id <chr>, user_location <chr>,
#> #   retweet_count <int>, like_count <int>, quote_count <int>,
#> #   user_tweet_count <int>, user_list_count <int>, …
```

<sup>Created on 2022-03-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by chainsawriot** [comment]
And the debugger points to this chunk of code.

https://github.com/TimBMK/academictwitteR/blob/abfec0d88c1958d80dacc6ecc1288a785365134e/R/bind_tweets.R#L264-L278

**Comment by TimBMK** [comment]
Yes, thanks for the pointers. I'm currently working on resolving the issues. It seems hk2 and 3 have a slightly different datastructure, but I didn't quite figure out how to solve it.

Other than that, I've added proper references to .data wherever applicable. I couldn't (yet?) resolve the colnames(.) instances, as colnames(.data) produces unexpected results. Also, dplyr's ":=" operator throws a notice, but I'm not entirely sure if its necessary (and possible) to import it from the package.

Finally, concerning naming conventions, I don't have any strong preferences. I'm renaming it to "tidy2" for now, but it's mostly up to you guys if you want to keep the differentiation, call it something else completely, or have it supersede the current "tidy" option. 

I'll update the code as soon as the errors are resolved

**Comment by chainsawriot** [comment]
@TimBMK The tidyverse's colon equal (darn, there are two, one from tidyverse another from data.table) is provided by `rlang`.

https://github.com/r-lib/rlang/blob/34b04a8a731b054de950ce885627898617e8b297/NAMESPACE#L104

And it is possible to import it

```r
@importFrom rlang :=
```

**Comment by TimBMK** [comment]
Great to know, thanks! Should I add the import in bind_tweets.R, an additional file (as with utils-pipe.R or the genereal utils.R? 

Also, I found the cause of the error. It seems some (older?) tweets do not provide the author ID the tweet.entities.mentions. Since, the author's username isn't usually provided for the sourcetweet, I'm currently reworking the function to resolve this issue. Handling of quotes will differ slightly from the current build (I'll have to note that down in the help file), but it should provide consisten behaviour across the board

**Comment by chainsawriot** [comment]
@TimBMK I think you simply insert it after here

https://github.com/cjbarrie/academictwitteR/blob/42e246e6a2bb88a1db59d05b5ced10782c6b1809/R/bind_tweets.R#L80

**Comment by TimBMK** [comment]
All test datasets seem to work now. Additionally, I fixed a bug and updated the help file. The bug related to .gen_raw() seems unrelated to this update. Rather, it seems it was introduced with the 0.3.1 update. I'll try to track it down and open an issue

**Comment by chainsawriot** [comment]
check

```text

❯ checking dependencies in R code ... WARNING
  '::' or ':::' import not declared from: ‘stringr’

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'bind_tweets'
    ‘vars’ ‘quoted_variables’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking R code for possible problems ... NOTE
  .add_quote_variables: no visible binding for global variable ‘.’
  .merge_rt_variables: no visible binding for global variable ‘.’
  convert_json: no visible binding for global variable ‘.’
  Undefined global functions or variables:
    .

❯ checking Rd line widths ... NOTE
  Rd file 'bind_tweets.Rd':
    \examples lines wider than 100 characters:
       # bind json files in the directory "data" into a "tidy2" data frame / tibble with additional variables
  
  These lines will be truncated in the PDF manual.

```

CHECK TODO

- [ ] undeclared `stringr` dependency
- [ ] Find a way to deal with the undefined global variable `.`
- [ ] Long RD line
- [ ] `vars` and `quote_variable`

**Comment by TimBMK** [comment]
The RD line and `vars`/`quoted_variables` issue should be fixed. 

I'm not sure how to go about the stringr dependency issue. Does it require to declare a general dependency on stringr somewhere? If so, where?

I still didn't find a way to deal with the `.` variable. It seems it has been used in academictwitteR's convert_json function before: https://github.com/cjbarrie/academictwitteR/blob/2809432aaea388e7bb016a1f15f24787e8d05586/R/bind_tweets.R#L85
How did you deal with it then?

**Comment by chainsawriot** [comment]
@TimBMK If you don't mind, I can deal with the undeclared dependency. 

The usage of `.` in the previous case is different from the current instances. In the previous case, it's a lambda (an anonymous function) while the current instances are actually `.`. I am still finding a way to deal with that.

**Comment by TimBMK** [comment]
Using the function myself, I also noticed a progress bar of some sort might be handy to keep track of the progress (comparable to output_format=NA bind_tweets version). As the process runs in parallel rather than in a loop, however, I'm not sure there's a straight forward way to implement that? 

Also, I tracked down the "Column id doesn't exist."-Bug: #304

**Comment by chainsawriot** [comment]
@TimBMK That's a nice suggestion. But please keep it at "one feature, one PR". Or else, it would be extremely difficult to dissect the git history later.

**Comment by cjbarrie** [comment]
Checking in on the status of this. Are we now working off #354 and can close this PR?

**Comment by TimBMK** [comment]
These are two seperate branches. #354 has the furrr-Support, but does not implement the tidy2 format. This branch here, however, has both the furrr-Support and the tidy2 format with additional variable output

**Comment by TimBMK** [comment]
This being said, the furrr-support for the updated bind_tweets-function is especially useful when using the tidy2 format, as the additional variables increase computing time (most noticeable on large datasets). I only made a seperate branch to make implementation easy; I am personally doing all my work on this branch, as I require the additional variables. It seems stable to me, but let me know if you need me to implement some tests or features in order to add it to the main build

**Comment by TimBMK** [comment]
I am assuming the test-coverage fails for the same reason as in #354. Other than that, the branch should be up to date with the latest master changes and ready to merge. For the tidy2 format, I've chosen a somewhat modular approach which allows users to select what type of data they want bound. This also comes in handy as the function becomes slower the more variables are added. This is somewhat remedied/handled by adding the furrr support (additional performance tweaks are welcome though). See benchmarks below. As this branch only adds the tidy2 format to bind_tweets(), it should leave everything else (including other formats) completely intact. It merely draws on the data already in the json files.

It does not solve #304 or #308, but should be somewhat compatible with their solutions as long as there is a "raw" format it can draw on (same as the tidy format). 

Let me know if you see any issues here or something requires additional changes to incorporate it better into the existing architecture. I've used the tidy2 format for months now and find the additional variables incredibly helpful in a number of research questions.

Benchmarks were run on a 6 thread windows machine. The sample data used for the read-in consists of 2413 tweets. While the tidy2 run binds all variables available (without the quoted variables), the "lessvars" run binds only "text", "user", and "hashtags".
```
Sequential Processing 
Unit: seconds
           expr       min        lq      mean    median        uq       max neval
            raw  3.572297  3.633977  3.664889  3.675744  3.708339  3.734087     5
           tidy 19.789128 19.961784 20.029804 20.055201 20.143502 20.199406     5
          tidy2 35.618186 35.640504 35.763637 35.656003 35.938915 35.964575     5
 tidy2_lessvars 25.268156 25.366674 25.441081 25.462428 25.468218 25.639927     5


Multisession Processing 
Unit: seconds
           expr      min       lq     mean   median       uq      max neval
            raw 3.472342 3.600961 3.715374 3.620421 3.827085 4.056062     5
           tidy 4.784946 4.874497 4.891205 4.894571 4.928706 4.973307     5
          tidy2 8.402214 8.517665 8.548699 8.591809 8.606562 8.625247     5
 tidy2_lessvars 5.923652 5.968713 6.458758 6.068273 6.116494 8.216660     5
```

**Comment by cjbarrie** [comment]
Sorry for being slow on this--term is in full swing right now. Can we overcome test-coverage in same way as we did before?

**Comment by TimBMK** [comment]
It might be the Git Secret again, @chainsawriot ?

**Comment by cjbarrie** [comment]
I have merged in anticipation of this repo being archived after new paid API endpoints introduced. And it's important to have this functionality for anyone binding already-processed tweets

**Comment by TimBMK** [comment]
Great, thanks. Yeah, let's hope there'll be an academic access left after the new changes....

**Pull request merged**
