### PR TITLE
deprecated warnings and user-related arguments

### PR DESCRIPTION
**Pull request by justinchuntingho**
Added deprecated warnings
Added user-related arguments to build_query()

### CODE REVIEW

**Comment by chainsawriot** [comment]
@justinchuntingho Should `get_geo_tweets` be deprecated as well?

**Comment by justinchuntingho** [comment]
I think this one is supposed to call an interactive menu to help setting bbox or radius, it doesn't really work when wrapped inside build_query and it might be worthwhile to separate this bit out. What do you think?

**Comment by chainsawriot** [comment]
I think it only adds `has:geo ` to a query, isn't it?

https://github.com/cjbarrie/academictwitteR/blob/master/R/get_geo_tweetsv2.R

**Comment by justinchuntingho** [comment]
You are right. They can be easily confused and I certainly did.

**Comment by chainsawriot** [comment]
I'll add some test cases to this.

**Pull request merged**
